### ISSUE TITLE
有没有数据？

### ISSUE THREAD

**Issue by flyuuu** [chenchiwei/tradaboost#1]
想问一下用的数据~~是什么

**Comment by chenchiwei** [comment]
数据是用某企业的金融风控数据

**Comment by xuxiaoqing2016** [comment]
能不能把数据也开源呢？没数据没办法运行呢？

**Comment by flyuuu** [comment]
好的，谢谢~~最近在学TL，多多交流啊~~

**Comment by chenchiwei** [comment]
多多交流

**Comment by xuxiaoqing2016** [comment]
请问您认为源域训练数据的分布和目标域训练数据的分布的特点是什么？论文中只提到了相似，但是我觉得相似这个特点并不好掌握，所以是不是可以理解为训练数据的差异对迁移学习的结果影响较大？也就是说可能用这些训练数据可以，但是换另外的训练数据就不可以了呢？

**Comment by yixinpei** [comment]
可否把数据也上传呢？或者给个sample

**Comment by chenchiwei** [comment]
数据可自行前往：https://www.kesci.com/apps/home/#!/competition/58e46b3b9ed26b1e09bfbbb7/content/0 下载
