### ISSUE TITLE
计算error的时候用的是目标域数据，你写的是源域数据吧。

### ISSUE THREAD

**Issue by zhengchu1994** [chenchiwei/tradaboost#18]
```
        error_rate = calculate_error_rate(label_S, result_label[row_A:row_A + row_S, i],
                                          weights[row_A:row_A + row_S, :])
```

**Comment by LaplaceZhang** [comment]
是的，这里需要修改，不然循环空转没有提升

            error_rate = self.calculate_error_rate(Target_label, result_label[:row_A, i],
                                                   weights[:row_A])
