### ISSUE TITLE
大家可以跑通吗？  我的怎么有ValueError: Input contains NaN, infinity 。。。。。。

### ISSUE THREAD

**Issue by mengchuangji** [chenchiwei/tradaboost#3]
总有这个错误：ValueError: Input contains NaN, infinity or a value too large for dtype('float64'). 大家有吗？怎么解决的

**Comment by mengchuangji** [comment]
问题解决了，原始数据的flag（lable）在EE列，应该放在训练数据的最后一列。

**Comment by Pyramiding** [comment]
原来如此
