### ISSUE TITLE
代码有可优化的地方

### ISSUE THREAD

**Issue by zhangjiantianyasmile** [chenchiwei/tradaboost#6]
代码作者，您好。
最近又重新仔细的看了你的代码还有戴文渊的算法，发现代码中的 test （测试样本）变量对建立或者优化模型并没有任何作用，戴的算法中也没有提到关于test的 一些计算。个人认为关于test 的计算可以省去。
如：train_classify（）函数中的test_data（trans_A+trans_S+test）只是用来做预测，而在预测返回的结果中只用到了result_label[row_A:row_A + row_S, i] （也就是trans_S的预测结果），trans_A和test的预测结果并没有用到，属非必要计算。
戴的算法中没有关于test的计算，个人认为可以在tradaboost（）函数中去除无关参数test，没必要浪费这些时空穿参。
最后冒昧问一下，之前在另一处评论下您给回复代码晚点更新，不知道您有没有抽出来时间更新下代码。最后的最后，非常感谢您提供这么优质的代码，谢谢~

**Comment by chenchiwei** [comment]
您好，感谢您对代码的reivew以及提出的建议，最近比较繁忙，很抱歉没有及时更新，这段时间会尽快更新；如果有需求，您也可以提交pull request，谢谢

**Comment by zhangjiantianyasmile** [comment]
您好，很抱歉，前面说的有点问题，关于test数据集只是在tradaboost（）函数最后做预测的时候用到了。迭代的时候可以省去test的预测。
